POSITION_CODES = {
    "B-S": "Backend · Senior",
    "B-M": "Backend · Middle",
    "B-J": "Backend · Junior",
    "F-S": "Frontend · Senior",
    "F-M": "Frontend · Middle",
    "F-J": "Frontend · Junior",
    "D-S": "DevOps · Senior",
    "D-M": "DevOps · Middle",
    "Q-S": "QA · Senior",
    "Q-M": "QA · Middle",
    "PM-S": "PM · Senior",
    "PM-M": "PM · Middle",
    "TL-S": "Team Lead · Senior",
}
