# Generated by Django 5.2.17 on 2026-09-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_issue_assignees_issue_customers_issue_watchers_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="status",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_review", True)),
                fields=("project",),
                name="one_review_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="status",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_review", False), ("category", "active"), _connector="OR"),
                name="review_is_active",
            ),
        ),
    ]
