# Generated by Django 5.2.17 on 2026-09-29 13:25

from django.db import migrations, models


def initialize_positions(apps, schema_editor):
    apps.get_model("projects", "Issue").objects.update(position=models.F("number"))


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_default_issue_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="position",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.RunPython(initialize_positions, migrations.RunPython.noop),
    ]
