# Generated by Django 5.2.17 on 2026-09-30 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0009_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Relation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("related", "Related task"),
                            ("blocks", "Blocks"),
                            ("parent", "Parent of"),
                        ],
                        max_length=12,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relations",
                        to="projects.issue",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relations",
                        to="projects.issue",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("source", models.F("target")), _negated=True),
                        name="relation_not_self",
                    ),
                    models.UniqueConstraint(
                        fields=("source", "target"), name="unique_relation_pair"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "parent")),
                        fields=("target",),
                        name="one_issue_parent",
                    ),
                ],
            },
        ),
    ]
